FROM node:22-alpine
WORKDIR /app

ARG PNPM_VERSION=9
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

ARG NEXT_PUBLIC_COGNITO_USER_POOL_ID
ARG NEXT_PUBLIC_COGNITO_CLIENT_ID
ARG COGNITO_REGION
ARG COGNITO_ISSUER
ENV NEXT_PUBLIC_COGNITO_USER_POOL_ID=${NEXT_PUBLIC_COGNITO_USER_POOL_ID}
ENV NEXT_PUBLIC_COGNITO_CLIENT_ID=${NEXT_PUBLIC_COGNITO_CLIENT_ID}
ENV COGNITO_REGION=${COGNITO_REGION}
ENV COGNITO_ISSUER=${COGNITO_ISSUER}

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
RUN pnpm run build

EXPOSE 3000
CMD ["pnpm","run","start"]